---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  log_level: <%= ENV['CHEF_LOG_LEVEL'] || 'auto' %>

platforms:
    - name: gannett/gci-centos-67
    - name: gannett/gci-centos-72

suites:
  - name: compliance # compliance direct reporting
    run_list:
      - recipe[audit::default]
    attributes:
      audit:
        server: <%= ENV['COMPLIANCE_API'] %>
        token: <%= ENV['COMPLIANCE_ACCESSTOKEN'] %>
        owner: admin
        profiles: &profiles
          base/ssh: true
          base/linux: true
